baseURL = 'https://febrianamir.github.io/'
languageCode = 'en-US'
title = 'Febrian Amir'

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  # [[menus.main]]
  #   name = 'Tags'
  #   pageRef = '/tags'
  #   weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
